SELECT 1 AS AGI_CLASS, '$1 and UNDER $25K' AGI_STUB,
UNION ALL
SELECT 2 AS AGI_CLASS, '$25K and UNDER $50K' AGI_STUB, 
UNION ALL
SELECT 3 AS AGI_CLASS, '$50K and UNDER $75K' AGI_STUB, 
UNION ALL
SELECT 4 AS AGI_CLASS, '$75K and UNDER $100K' AGI_STUB,
UNION ALL
SELECT 5 AS AGI_CLASS, '$100K and UNDER $200K' AGI_STUB, 
UNION ALL
SELECT 6 AS AGI_CLASS, '$200K or MORE' AGI_STUB
