models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    data_tests:
      - minimum_row_count:
          arguments:
            minimum_row_count: 1000
          severity: error
    columns:

     - name: listing_id
       description: This is primay key
       data_tests:
         - unique
         - not_null

     - name: host_id
       description: The host's id. References the host table.
       data_tests:
         - not_null
         - relationships:
             arguments:
               to: ref('dim_hosts_cleansed')
               field: host_id

     - name: room_type
       description: Type of the apartment / room
       data_tests:
         - accepted_values:
             arguments:
               values: ['Entire home/apt',
                        'Private room',
                        'Shared room',
                        'Hotel room']

     - name: minimum_nights
       description: "{{ doc('dim_listing_cleansed__minimum_nights') }}"
       data_tests:
          - positive_values
                      
  - name: dim_hosts_cleansed
    description: Cleansed table which contains Airbnb hosts.

    columns:
      - name: host_id
        description: This is host primary key
        data_tests:
          - not_null
          - unique

      - name: host_name
        description: Host Name
        data_tests:
          - not_null
      - name: is_superhost
        description: True or False if the host is super host.
        data_tests:
          - accepted_values:
              arguments:
                values: ['t', 'f']